name: Stock Alert

on:
  workflow_dispatch:  # This allows manual triggering of the workflow
  schedule:
    - cron: '0 21 * * 1-4'  # Runs at 9 PM UTC Monday to Thursday
    - cron: '0 21 * * 5'  # Runs at 9 PM UTC on Friday

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        node-version: '20'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        node-version: '20'

    - name: Decode and write GCP credentials
      run: |
        echo ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} | base64 --decode > $HOME/gcp-key.json

    - name: Install dependencies
      run: |
        pip install --upgrade yfinance gspread oauth2client

    - name: Run stock alert script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-key.json
      run: python your_script.py
